[package]
name = "xtended-iter"
version = "0.0.1"
description = "A library to extend the functionality of the base Iter"
repository = "https://github.com/edjCase/motoko_iter"
keywords = [ "iter", "iterator", "array" ]
license = "MIT"

[dependencies]
new-base = "0.4.0"

[dev-dependencies]
test = "2.1.1"
